codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: up
  range: "70...100"

  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 1%
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: false
