[Main]
name   = "Aura"
mode   = "dark"
author = "Myian"
credit = "Dalton Menezes"
url    = "https://github.com/daltonmenezes/aura-theme"

[Base]
base    = "#15141b"
default = "#edecee"
faded   = "#888888"
red     = "#ff6767"
orange  = "#ff9341"
yellow  = "#ffca85"
green   = "#8ae986"
cyan    = "#61ffca"
blue    = "#82e2ff"
purple  = "#a277ff"

[Project]
root     = "default"
folder   = "red"
file     = "default"
title    = "cyan"
chapter  = "purple"
scene    = "#f694ff"
note     = "yellow"
active   = "cyan"
inactive = "red"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "cyan"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "cyan"
create    = "yellow"
destroy   = "faded"
reset     = "cyan"
add       = "cyan"
change    = "cyan"
remove    = "red"
shortcode = "yellow"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#0c0c11"
windowText      = "default"
base            = "base"
alternateBase   = "#353249"
text            = "default"
tooltipBase     = "yellow"
tooltipText     = "base"
button          = "base:L125"
buttonText      = "default"
brightText      = "base"
highlight       = "#603bb1"
highlightedText = "default"
link            = "blue"
linkVisited     = "blue"
accent          = "#603bb1"
toggle          = "#462392"
searchMatch     = "yellow:80"

[GUI]
helpText  = "faded:L125"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "#29263c"
link           = "blue"
headerText     = "cyan"
headerTag      = "cyan:128"
emphasis       = "purple:L105"
whitespace     = "purple:64"
dialog         = "cyan"
altDialog      = "blue"
note           = "yellow"
hidden         = "faded"
shortcode      = "yellow"
keyword        = "#f694ff"
tag            = "yellow"
value          = "faded"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "blue"
replaceTag     = "yellow"
modifier       = "red"
textHighlight  = "#3c3958"
