[Main]
name   = "Aura Soft"
mode   = "dark"
author = "Myian"
credit = "Dalton Menezes"
url    = "https://github.com/daltonmenezes/aura-theme"

[Base]
base    = "#21202e"
default = "#bdbdbd"
faded   = "#6d6d6d"
red     = "#c55858"
orange  = "#e0925d"
yellow  = "#d8af79"
green   = "#6fb16d"
cyan    = "#54c59f"
blue    = "#6cb2c7"
purple  = "#8464c6"

[Project]
root     = "default"
folder   = "red"
file     = "default"
title    = "cyan"
chapter  = "purple"
scene    = "#f694ff"
note     = "yellow"
active   = "cyan"
inactive = "red"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "cyan"
reject    = "red"
action    = "blue"
altAction = "orange"
apply     = "cyan"
create    = "yellow"
destroy   = "faded"
reset     = "cyan"
add       = "cyan"
change    = "cyan"
remove    = "red"
shortcode = "yellow"
markdown  = "default"
systemIO  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#191924"
windowText      = "default"
base            = "base"
alternateBase   = "#353249"
text            = "default"
tooltipBase     = "yellow"
tooltipText     = "base"
button          = "base:L125"
buttonText      = "default"
brightText      = "base"
highlight       = "#6a4da3"
highlightedText = "#edecee"
link            = "blue"
linkVisited     = "blue"
accent          = "#6a4da3"
toggle          = "#381f6b"
searchMatch     = "yellow:80"

[GUI]
helpText  = "faded:L125"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "#29263c"
link           = "blue"
headerText     = "cyan"
headerTag      = "cyan:128"
emphasis       = "#a581ec"
whitespace     = "#a581ec64"
dialog         = "cyan"
altDialog      = "blue"
note           = "yellow"
hidden         = "faded"
shortcode      = "yellow"
keyword        = "#c17ac8"
tag            = "yellow"
value          = "faded"
optional       = "faded"
spellCheckLine = "#ff6767"
errorLine      = "#82e2ff"
replaceTag     = "yellow"
modifier       = "red"
textHighlight  = "#3c3958"
