[Main]
name   = "B2T Suburb Light"
mode   = "light"
author = "Myian"
credit = "Bram de Haan"
url    = "https://base2t.one/demo/suburb/"

[Base]
base    = "#fbf9fa"
default = "#444864"
faded   = "#878ba6"
red     = "#d14781"
orange  = "#d38152"
yellow  = "#cac63a"
green   = "#378d60"
cyan    = "#308ab1"
blue    = "#5165e6"
purple  = "#9958be"

[Project]
root     = "default"
folder   = "faded"
file     = "#b0a5a9"
title    = "red"
chapter  = "#f764a1"
scene    = "#ff99c3"
note     = "#8696fd"
active   = "red"
inactive = "faded"
disabled = "#b6bad1"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "blue"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#e9e5e7"
windowText      = "default"
base            = "base"
alternateBase   = "#d7cbd0"
text            = "default"
tooltipBase     = "#d2d8fe"
tooltipText     = "default"
button          = "#fbf9fa"
buttonText      = "default"
brightText      = "base"
highlight       = "#f764a1"
highlightedText = "base"
link            = "blue"
linkVisited     = "blue"
accent          = "#fe81b5"
toggle          = "#fe81b57f"
searchMatch     = "#fe81b57f"

[GUI]
helpText  = "#65697c"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "#6e7396"
line           = "#eae1e5"
link           = "blue"
headerText     = "red"
headerTag      = "red:128"
emphasis       = "#1e202f"
whitespace     = "#1e202f64"
dialog         = "red"
altDialog      = "#fb6fa9"
note           = "blue"
hidden         = "blue"
shortcode      = "#8696fd"
keyword        = "faded"
tag            = "blue"
value          = "default"
optional       = "faded"
spellCheckLine = "#ff0000"
errorLine      = "cyan"
replaceTag     = "blue"
modifier       = "faded"
textHighlight  = "#f25a9944"
