[Main]
name   = "B2T Garden Light"
mode   = "light"
author = "Myian"
credit = "Bram de Haan"
url    = "https://base2t.one/demo/garden/"

[Base]
base    = "#fbfaf8"
default = "#505350"
faded   = "#969c96"
red     = "#df6547"
orange  = "#db9257"
yellow  = "#cccc58"
green   = "#3fac39"
cyan    = "#5dacc9"
blue    = "#7678d4"
purple  = "#d362a8"

[Project]
root     = "default"
folder   = "orange"
file     = "default"
title    = "#6bcc66"
chapter  = "#3fac39"
scene    = "#1c8217"
note     = "faded"
active   = "green"
inactive = "orange"
disabled = "#aab1aa"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
altAction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "orange"
markdown  = "default"
systemIO  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#ece5df"
windowText      = "default"
base            = "base"
alternateBase   = "#dbd0c7"
text            = "default"
tooltipBase     = "#dcf0db"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#4cb946"
highlightedText = "base"
link            = "#1c8217"
linkVisited     = "#1c8217"
accent          = "#bd5d0f"
toggle          = "#bd5d0f60"
searchMatch     = "#d9772660"

[GUI]
helpText  = "#696d69"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "#f0ebe6"
link           = "blue"
headerText     = "#2b2c2a"
headerTag      = "#828782"
emphasis       = "#4cb946"
whitespace     = "#4cb94664"
dialog         = "#1c8217"
altDialog      = "#3fac39"
note           = "#d97726"
hidden         = "faded"
shortcode      = "#d97726"
keyword        = "#d97726"
tag            = "#bd5d0f"
value          = "#bd5d0f"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "green"
replaceTag     = "#d97726"
modifier       = "faded"
textHighlight  = "green:80"
