[Main]
name   = "B2T Suburb Dark"
mode   = "dark"
author = "Myian"
credit = "Bram de Haan"
url    = "https://base2t.one/demo/suburb/"

[Base]
base    = "#25293d"
default = "#d7dbf3"
faded   = "#888eaf"
red     = "#fb6fa9"
orange  = "#ff9b7d"
yellow  = "#ffdf8f"
green   = "#8bd59d"
cyan    = "#76cde3"
blue    = "#8696fd"
purple  = "#de95ee"

[Project]
root     = "default"
folder   = "faded"
file     = "#b0a6aa"
title    = "#d14781"
chapter  = "#f764a1"
scene    = "#ff99c3"
note     = "#8696fd"
active   = "red"
inactive = "faded"
disabled = "#575c79"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
altAction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "#a0acfe"
systemIO  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#1e212f"
windowText      = "default"
base            = "base"
alternateBase   = "#444864"
text            = "default"
tooltipBase     = "#d2d8fe"
tooltipText     = "base"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "red"
highlightedText = "#1e202f"
link            = "blue"
linkVisited     = "blue"
accent          = "red"
toggle          = "red:128"
searchMatch     = "red:128"

[GUI]
helpText  = "#9b9fb6"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "#b1b7d9"
line           = "#373a51"
link           = "blue"
headerText     = "red"
headerTag      = "red:128"
emphasis       = "#ffffff"
whitespace     = "#ffffff64"
dialog         = "#fe81b5"
altDialog      = "#ffb3d2"
note           = "#a0acfe"
hidden         = "blue"
shortcode      = "#6375ee"
keyword        = "faded"
tag            = "#a0acfe"
value          = "default"
optional       = "faded"
spellCheckLine = "#ff3b3b"
errorLine      = "#7083ff"
replaceTag     = "blue"
modifier       = "faded"
textHighlight  = "red:72"
