[Main]
name   = "B4T Classic-O Light"
mode   = "light"
author = "Myian"
credit = "Bram de Haan"
url    = "https://atelierbram.github.io/Base4Tone-prism/b4t_classic-o/light/"

[Base]
base    = "#f6f7f9"
default = "#333b47"
faded   = "#718098"
red     = "#c03b6e"
orange  = "#c46d26"
yellow  = "#bb8e46"
green   = "#3d9e29"
cyan    = "#039582"
blue    = "#4187f5"
purple  = "#aa52e0"

[Project]
root     = "default"
folder   = "blue"
file     = "faded"
title    = "#007061"
chapter  = "#039582"
scene    = "#1abba6"
note     = "#c17eed"
active   = "default"
inactive = "faded"
disabled = "#acb5c3"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "cyan"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "cyan"
create    = "yellow"
destroy   = "faded"
reset     = "cyan"
add       = "cyan"
change    = "cyan"
remove    = "red"
shortcode = "purple"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#e7eaee"
windowText      = "default"
base            = "base"
alternateBase   = "#d0d5dd"
text            = "default"
tooltipBase     = "#ffe8c4"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#0c9c89"
highlightedText = "base"
link            = "blue"
linkVisited     = "blue"
accent          = "#0c9c89"
toggle          = "#0c9c897f"
searchMatch     = "#e6c8f9"

[GUI]
helpText  = "default:192"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "#dcdfe4"
link           = "blue"
headerText     = "cyan"
headerTag      = "cyan:128"
emphasis       = "#008976"
whitespace     = "#00897664"
dialog         = "#1a68e5"
altDialog      = "#1249a0"
note           = "#c17eed"
hidden         = "faded"
shortcode      = "purple"
keyword        = "#6555e0"
tag            = "#9488f2"
value          = "faded"
optional       = "faded"
spellCheckLine = "#ff2259"
errorLine      = "blue"
replaceTag     = "#7e6fe5"
modifier       = "purple"
textHighlight  = "cyan:64"
