[Main]
name   = "Castle by Night"
mode   = "dark"
author = "Myian"

[Base]
base    = "#1c1f28"
default = "#d6d6d6"
faded   = "#878a91"
red     = "#fa8080"
orange  = "#ee9c70"
yellow  = "#fadd8d"
green   = "#afd49d"
cyan    = "#a4dad7"
blue    = "#9cb2ec"
purple  = "#d296d4"

[Project]
root     = "default"
folder   = "blue"
file     = "red"
title    = "green"
chapter  = "yellow"
scene    = "orange"
note     = "#9b9ea5"
active   = "default"
inactive = "faded"
disabled = "#4b4f5c"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "orange"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base:D130"
windowText      = "default"
base            = "base"
alternateBase   = "base:L160"
text            = "default"
tooltipBase     = "yellow:L120"
tooltipText     = "base"
button          = "base:L110"
buttonText      = "default"
brightText      = "base"
highlight       = "red:D150"
highlightedText = "default:L110"
link            = "blue"
linkVisited     = "blue"
accent          = "red:D150"
toggle          = "#2c3c6b"
searchMatch     = "#3d496b"

[GUI]
helpText  = "faded"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "base:L150"
link           = "blue"
headerText     = "yellow"
headerTag      = "yellow:160"
emphasis       = "yellow"
whitespace     = "yellow:64"
dialog         = "green"
altDialog      = "cyan"
note           = "faded"
hidden         = "faded"
shortcode      = "faded"
keyword        = "red"
tag            = "orange"
value          = "#e4b2e6"
optional       = "orange:L120"
spellCheckLine = "#ff5d5d"
errorLine      = "cyan"
replaceTag     = "blue"
modifier       = "purple"
textHighlight  = "red:72"
