[Main]
name   = "Chernozem"
mode   = "dark"
author = "Myian"

[Base]
base    = "#2c2525"
default = "#dad0ca"
faded   = "#857972"
red     = "#e06c6c"
orange  = "#ec935f"
yellow  = "#e5cc91"
green   = "#6e9e6a"
cyan    = "#72b69f"
blue    = "#7c9fbd"
purple  = "#c899d6"

[Project]
root     = "default"
folder   = "green"
file     = "default"
title    = "red"
chapter  = "orange"
scene    = "yellow"
note     = "blue"
active   = "green"
inactive = "faded"
disabled = "#504742"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "orange"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#241d1d"
windowText      = "default"
base            = "base"
alternateBase   = "faded:80"
text            = "default"
tooltipBase     = "yellow"
tooltipText     = "base"
button          = "#362c2b"
buttonText      = "default"
brightText      = "base"
highlight       = "#6ca167"
highlightedText = "#241d1d"
link            = "blue"
linkVisited     = "blue"
accent          = "#5a8d55"

[GUI]
helpText    = "#a39891"
fadedText   = "faded"
errorText   = "red"
toggle      = "#5a8d557f"
searchMatch = "red:96"

[Syntax]
background     = "base"
text           = "default"
line           = "faded:48"
link           = "blue"
headerText     = "red"
headerTag      = "red:128"
emphasis       = "#85c47f"
whitespace     = "#85c47f64"
dialog         = "orange"
altDialog      = "yellow"
note           = "faded"
hidden         = "faded"
shortcode      = "blue"
keyword        = "blue"
tag            = "#a1c4e4"
value          = "#a1c4e4"
optional       = "faded"
spellCheckLine = "#ff5555"
errorLine      = "cyan"
replaceTag     = "purple"
modifier       = "blue"
textHighlight  = "green:80"
