[Main]
name   = "Default Light Theme"
mode   = "light"
author = "Veronica Berglyd Olsen"
credit = "Veronica Berglyd Olsen"
url    = "https://github.com/vkbo/novelWriter"

[Base]
base    = "#fcfcfc"
default = "#303030"
faded   = "#6c6c6c"
red     = "#a62a2d"
orange  = "#b36829"
yellow  = "#a39c34"
green   = "#296629"
cyan    = "#269999"
blue    = "#3a70a6"
purple  = "#b35ab3"

[Project]
root     = "blue"
folder   = "yellow"
file     = "default"
title    = "green"
chapter  = "red"
scene    = "blue"
note     = "yellow"
active   = "green"
inactive = "red"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
altAction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "orange"
systemIO  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base:D105"
windowText      = "default"
base            = "base"
alternateBase   = "#e0e0e0"
text            = "default"
tooltipBase     = "#ffffc0"
tooltipText     = "#15150d"
button          = "#efefef"
buttonText      = "default"
brightText      = "base"
highlight       = "#3087c6"
highlightedText = "base"
link            = "blue"
linkVisited     = "blue"
accent          = "#3087c6"
toggle          = "blue:96"
searchMatch     = "orange:96"

[GUI]
helpText  = "#5c5c5c"
fadedText = "#6c6c6c"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "default:32"
link           = "blue"
headerText     = "green"
headerTag      = "green:L135"
emphasis       = "orange"
whitespace     = "orange:64"
dialog         = "blue"
altDialog      = "red"
note           = "yellow:D125"
hidden         = "faded"
shortcode      = "blue"
keyword        = "red"
tag            = "green"
value          = "green"
optional       = "blue"
spellCheckLine = "red"
errorLine      = "green"
replaceTag     = "green"
modifier       = "blue"
textHighlight  = "yellow:72"
