[Main]
name   = "Default Dark Theme"
mode   = "dark"
author = "Veronica Berglyd Olsen"
credit = "Veronica Berglyd Olsen"
url    = "https://github.com/vkbo/novelWriter"

[Base]
base    = "#373737"
default = "#cccccc"
faded   = "#949494"
red     = "#ff6666"
orange  = "#ff9966"
yellow  = "#ffcc66"
green   = "#99cc99"
cyan    = "#66cccc"
blue    = "#6699cc"
purple  = "#cc99cc"

[Project]
root     = "blue"
folder   = "yellow"
file     = "default"
title    = "green"
chapter  = "red"
scene    = "blue"
note     = "yellow"
active   = "green"
inactive = "red"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
altAction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "orange"
systemIO  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base:L125"
windowText      = "default"
base            = "base"
alternateBase   = "#4e4e4e"
text            = "default"
tooltipBase     = "#ffffc0"
tooltipText     = "#15150d"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#2c98f7"
highlightedText = "#ffffff"
link            = "blue"
linkVisited     = "blue"
accent          = "#2c98f7"
toggle          = "blue:128"
searchMatch     = "orange:96"

[GUI]
helpText  = "#a4a4a4"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "default:32"
link           = "blue"
headerText     = "green"
headerTag      = "green:D150"
emphasis       = "orange"
whitespace     = "orange:64"
dialog         = "blue"
altDialog      = "red"
note           = "yellow"
hidden         = "faded"
shortcode      = "blue"
keyword        = "red"
tag            = "green"
value          = "green"
optional       = "blue"
spellCheckLine = "red"
errorLine      = "green"
replaceTag     = "green"
modifier       = "blue"
textHighlight  = "yellow:72"
