[Main]
name   = "Everforest Dark"
mode   = "dark"
author = "Myian"
credit = "Sainnhe Park"
url    = "https://github.com/sainnhe/everforest"

[Base]
base    = "#272e33"
default = "#d3c6aa"
faded   = "#859289"
red     = "#e67e80"
orange  = "#e69875"
yellow  = "#dbbc7f"
green   = "#a7c080"
cyan    = "#83c092"
blue    = "#7fbbb3"
purple  = "#d699b6"

[Project]
root     = "default"
folder   = "orange"
file     = "red"
title    = "green"
chapter  = "blue"
scene    = "purple"
note     = "faded"
active   = "cyan"
inactive = "orange"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "orange"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#1e2326"
windowText      = "default"
base            = "base"
alternateBase   = "#374145"
text            = "default"
tooltipBase     = "yellow"
tooltipText     = "base"
button          = "#2e383c"
buttonText      = "default"
brightText      = "base"
highlight       = "#a7c080"
highlightedText = "base"
link            = "blue"
linkVisited     = "blue"
accent          = "#a7c080"
toggle          = "#a7c0807f"
searchMatch     = "orange:80"

[GUI]
helpText  = "#a9a49d"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "#343f44"
link           = "blue"
headerText     = "cyan"
headerTag      = "cyan:128"
emphasis       = "blue"
whitespace     = "blue:64"
dialog         = "green"
altDialog      = "cyan"
note           = "purple"
hidden         = "faded"
shortcode      = "orange"
keyword        = "orange"
tag            = "purple"
value          = "faded"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "cyan"
replaceTag     = "purple"
modifier       = "red"
textHighlight  = "cyan:72"
