[Main]
name   = "Floral Daydream"
mode   = "light"
author = "Myian"

[Base]
base    = "#fff4f7"
default = "#ac3b6f"
faded   = "#c285aa"
red     = "#e76b6d"
orange  = "#e08b46"
yellow  = "#cca333"
green   = "#59976b"
cyan    = "#5d9ea3"
blue    = "#658cc5"
purple  = "#9d77c9"

[Project]
root     = "default"
folder   = "yellow"
file     = "orange"
title    = "blue"
chapter  = "purple"
scene    = "red"
note     = "#6dad7f"
active   = "green"
inactive = "faded"
disabled = "#e2bcce"

[Icon]
tool      = "default"
sidebar   = "#ca3c72"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "orange"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#ffe3ea"
windowText      = "default"
base            = "base"
alternateBase   = "#ffc7d8"
text            = "default"
tooltipBase     = "#fff0ba"
tooltipText     = "#413309"
button          = "#ffffff"
buttonText      = "default"
brightText      = "base"
highlight       = "#e4688d"
highlightedText = "#ffffff"
link            = "#4781d8"
linkVisited     = "#4781d8"
accent          = "#e4688d"

[GUI]
helpText    = "#d14a73"
fadedText   = "faded"
errorText   = "red"
toggle      = "#e4688d7f"
searchMatch = "#e4688d50"

[Syntax]
background     = "base"
text           = "#5f3a50"
line           = "#ffdbe4"
link           = "#4781d8"
headerText     = "#4781d8"
headerTag      = "#4781d880"
emphasis       = "#8152b8"
whitespace     = "#8152b864"
dialog         = "#eb4073"
altDialog      = "#4781d8"
note           = "#31924c"
hidden         = "faded"
shortcode      = "#31924c"
keyword        = "#1a6d32"
tag            = "#31924c"
value          = "#ce7b1d"
optional       = "faded"
spellCheckLine = "#ff0000"
errorLine      = "#1a6d32"
replaceTag     = "#31924c"
modifier       = "#1a6d32"
textHighlight  = "#bae2c5"
