[Main]
name   = "Full Moon"
mode   = "light"
author = "Myian"

[Base]
base    = "#ffffff"
default = "#37404e"
faded   = "#93a2a8"
red     = "#d35654"
orange  = "#d17a09"
yellow  = "#caac00"
green   = "#579220"
cyan    = "#1b948a"
blue    = "#2d78b9"
purple  = "#c45fb3"

[Project]
root     = "default"
folder   = "orange"
file     = "purple"
title    = "green"
chapter  = "red"
scene    = "blue"
note     = "yellow"
active   = "green"
inactive = "red"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
altAction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "blue"
systemIO  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#e7ebee"
windowText      = "default"
base            = "base"
alternateBase   = "#d4d9dd"
text            = "default"
tooltipBase     = "#ffeea6"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#5495ce"
highlightedText = "base"
link            = "blue"
linkVisited     = "blue"
accent          = "#5495ce"
toggle          = "#5495ce7f"
searchMatch     = "default:64"

[GUI]
helpText  = "#586a72"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "#586a72"
line           = "#e7ebee"
link           = "blue"
headerText     = "purple"
headerTag      = "purple:128"
emphasis       = "blue"
whitespace     = "blue:64"
dialog         = "#0e2a35"
altDialog      = "cyan"
note           = "green"
hidden         = "faded"
shortcode      = "#c5931f"
keyword        = "#c5931f"
tag            = "red"
value          = "orange"
optional       = "#c5931f"
spellCheckLine = "#f73c3f"
errorLine      = "cyan"
replaceTag     = "purple"
modifier       = "#c5931f"
textHighlight  = "blue:80"
