[Main]
name   = "Grey Dark"
mode   = "dark"
author = "Veronica Berglyd Olsen"
credit = "Veronica Berglyd Olsen"
url    = "https://github.com/vkbo/novelWriter"

[Base]
base    = "#3e3e3e"
default = "#c8c8c8"
faded   = "#949494"
red     = "#f2777a"
orange  = "#f99139"
yellow  = "#ffcc66"
green   = "#99cc99"
cyan    = "#66cccc"
blue    = "#6699cc"
purple  = "#cc99cc"

[Project]
root     = "blue"
folder   = "yellow"
file     = "default"
title    = "green"
chapter  = "red"
scene    = "blue"
note     = "yellow"
active   = "green"
inactive = "red"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
altAction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "orange"
systemIO  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#363636"
windowText      = "default"
base            = "base"
alternateBase   = "#4e4e4e"
text            = "default"
tooltipBase     = "#ffffc0"
tooltipText     = "#15150d"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#2c98f7"
highlightedText = "#ffffff"
link            = "blue"
linkVisited     = "blue"
accent          = "#2c98f7"
toggle          = "#9999997f"
searchMatch     = "#9999997f"

[GUI]
helpText  = "default:D120"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "#363636"
text           = "default"
line           = "default:32"
link           = "default"
headerText     = "default:L115"
headerTag      = "default:D125"
emphasis       = "default"
whitespace     = "default:64"
dialog         = "default"
altDialog      = "default"
note           = "default"
hidden         = "faded"
shortcode      = "default:L115"
keyword        = "default:L115"
tag            = "default"
value          = "default"
optional       = "default:L115"
spellCheckLine = "red"
errorLine      = "green"
replaceTag     = "default:L115"
modifier       = "default:L115"
textHighlight  = "#ffffff40"
