[Main]
name   = "Horizon Dark"
mode   = "dark"
author = "Myian"
credit = "Jonathan Olaleye"
url    = "https://github.com/jolaleye/horizon-theme-vscode"

[Base]
base    = "#1c1e26"
default = "#d5d8da"
faded   = "#6c6f93"
red     = "#e95678"
orange  = "#f09383"
yellow  = "#fac29a"
green   = "#ace77b"
cyan    = "#27d796"
blue    = "#25b2bc"
purple  = "#b877db"

[Project]
root     = "default"
folder   = "purple"
file     = "yellow"
title    = "blue"
chapter  = "red"
scene    = "orange"
note     = "faded"
active   = "yellow"
inactive = "faded"
disabled = "#404263"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "cyan"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "cyan"
create    = "yellow"
destroy   = "faded"
reset     = "cyan"
add       = "cyan"
change    = "cyan"
remove    = "red"
shortcode = "default"
markdown  = "orange"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#2e303e"
text            = "default"
tooltipBase     = "yellow"
tooltipText     = "base"
button          = "#232530"
buttonText      = "default"
brightText      = "base"
highlight       = "#fab28e"
highlightedText = "base"
link            = "#21bfc2"
linkVisited     = "#21bfc2"
accent          = "#fab28e"
toggle          = "#393c5f"
searchMatch     = "purple:104"

[GUI]
helpText  = "default:192"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "#232530"
link           = "blue"
headerText     = "red"
headerTag      = "red:128"
emphasis       = "yellow"
whitespace     = "yellow:64"
dialog         = "orange"
altDialog      = "red"
note           = "blue"
hidden         = "faded"
shortcode      = "blue"
keyword        = "purple"
tag            = "blue"
value          = "faded"
optional       = "faded"
spellCheckLine = "#ff3d5d"
errorLine      = "cyan"
replaceTag     = "blue"
modifier       = "purple"
textHighlight  = "orange:80"
