[Main]
name   = "Jewel Case Light"
mode   = "light"
author = "Myian"

[Base]
base    = "#e1e7ec"
default = "#2a3744"
faded   = "#768997"
red     = "#be4255"
orange  = "#ce5c27"
yellow  = "#ca8300"
green   = "#379152"
cyan    = "#129696"
blue    = "#2973c7"
purple  = "#9161c5"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "purple"
chapter  = "green"
scene    = "#2e6b3f"
note     = "faded"
active   = "default"
inactive = "faded"
disabled = "#abbac7"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "green"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#bac7d1"
text            = "default"
tooltipBase     = "#fff8bc"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#d15b6d"
highlightedText = "#ffffff"
link            = "blue"
linkVisited     = "blue"
accent          = "#d15b6d"
toggle          = "#a9d1ff"
searchMatch     = "green:80"

[GUI]
helpText  = "#596b7e"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "#f6f9fc"
text           = "default"
line           = "base"
link           = "blue"
headerText     = "#000000"
headerTag      = "faded"
emphasis       = "green"
whitespace     = "blue:64"
dialog         = "#1c5a8d"
altDialog      = "cyan"
note           = "red"
hidden         = "faded"
shortcode      = "#2e6b3f"
keyword        = "#8f5509"
tag            = "#af7200"
value          = "#000000"
optional       = "cyan"
spellCheckLine = "#d15b6d"
errorLine      = "cyan"
replaceTag     = "red"
modifier       = "#991635"
textHighlight  = "blue:80"
