[Main]
name   = "Jewel Case Dark"
mode   = "dark"
author = "Myian"

[Base]
base    = "#191f2c"
default = "#cdd9e4"
faded   = "#56687c"
red     = "#d47d8c"
orange  = "#e7a172"
yellow  = "#eee7aa"
green   = "#7cc08b"
cyan    = "#6acfc7"
blue    = "#6793e4"
purple  = "#bc90d6"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "purple"
chapter  = "#548d60"
scene    = "green"
note     = "faded"
active   = "default"
inactive = "faded"
disabled = "#2b374e"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
altAction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "green"
systemIO  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#2a364d"
text            = "default"
tooltipBase     = "yellow"
tooltipText     = "base"
button          = "#161f31"
buttonText      = "default"
brightText      = "base"
highlight       = "#a85066"
highlightedText = "#ffffff"
link            = "blue"
linkVisited     = "blue"
accent          = "#a85066"
toggle          = "#113579"
searchMatch     = "green:104"

[GUI]
helpText  = "#8297ad"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "#141925"
text           = "default"
line           = "#1d2636"
link           = "blue"
headerText     = "#ffffff"
headerTag      = "faded"
emphasis       = "green"
whitespace     = "blue:72"
dialog         = "#91b7dd"
altDialog      = "cyan"
note           = "red"
hidden         = "faded"
shortcode      = "#548d60"
keyword        = "#b3a66e"
tag            = "#fff8bc"
value          = "#ffffff"
optional       = "cyan"
spellCheckLine = "red"
errorLine      = "cyan"
replaceTag     = "red"
modifier       = "#a85066"
textHighlight  = "blue:80"
