[Main]
name   = "LCARS"
mode   = "dark"
author = "Veronica Berglyd Olsen"
credit = "Star Trek TNG"
url    = "https://github.com/vkbo/novelWriter"

[Base]
base    = "#101010"
default = "#c7c7c7"
faded   = "#757575"
red     = "#e24d5f"
orange  = "#ff9902"
yellow  = "#ffdc59"
green   = "#54e985"
cyan    = "#7ffff2"
blue    = "#009cff"
purple  = "#8aa5ff"

[Project]
root     = "orange"
folder   = "yellow"
file     = "default"
title    = "green"
chapter  = "red"
scene    = "blue"
note     = "yellow"
active   = "blue"
inactive = "red"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
altAction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "orange"
systemIO  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base:L180"
windowText      = "default"
base            = "base"
alternateBase   = "base:L300"
text            = "default"
tooltipBase     = "yellow:L140"
tooltipText     = "base"
button          = "base:L140"
buttonText      = "default"
brightText      = "base"
highlight       = "purple"
highlightedText = "base"
link            = "purple"
linkVisited     = "purple"
accent          = "orange"
toggle          = "orange:96"
searchMatch     = "red:96"

[GUI]
helpText  = "blue"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "yellow:48"
link           = "purple"
headerText     = "orange"
headerTag      = "red"
emphasis       = "orange"
whitespace     = "orange:64"
dialog         = "yellow"
altDialog      = "green"
note           = "purple"
hidden         = "faded"
shortcode      = "purple"
keyword        = "red"
tag            = "orange"
value          = "orange"
optional       = "purple"
spellCheckLine = "red"
errorLine      = "red"
replaceTag     = "purple"
modifier       = "red"
textHighlight  = "orange:96"
