[Main]
name   = "New Moon"
mode   = "dark"
author = "Myian"
credit = "Tania Rascia"
url    = "https://github.com/taniarascia/new-moon"

[Base]
base    = "#2d2d2d"
default = "#d1d7e0"
faded   = "#777c85"
red     = "#f2777a"
orange  = "#fca369"
yellow  = "#ffeea6"
green   = "#92d192"
cyan    = "#76d4d6"
blue    = "#6ab0f3"
purple  = "#e1a6f2"

[Project]
root     = "default"
folder   = "orange"
file     = "purple"
title    = "green"
chapter  = "red"
scene    = "blue"
note     = "yellow"
active   = "green"
inactive = "red"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "blue"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#252525"
windowText      = "default"
base            = "base"
alternateBase   = "#444444"
text            = "default"
tooltipBase     = "yellow"
tooltipText     = "base"
button          = "#2d2d2d"
buttonText      = "default"
brightText      = "base"
highlight       = "#4386c5"
highlightedText = "#ffffff"
link            = "blue"
linkVisited     = "blue"
accent          = "#4386c5"

[GUI]
helpText    = "#999eaa"
fadedText   = "faded"
errorText   = "red"
toggle      = "#4386c57f"
searchMatch = "default:80"

[Syntax]
background     = "base"
text           = "#b3b9c5"
line           = "#444444"
link           = "blue"
headerText     = "purple"
headerTag      = "purple:128"
emphasis       = "blue"
whitespace     = "blue:64"
dialog         = "#ffffff"
altDialog      = "cyan"
note           = "green"
hidden         = "faded"
shortcode      = "yellow"
keyword        = "yellow"
tag            = "red"
value          = "#ffd479"
optional       = "yellow"
spellCheckLine = "#ff6265"
errorLine      = "green"
replaceTag     = "purple"
modifier       = "yellow"
textHighlight  = "blue:80"
