[Main]
name   = "Nordlicht"
mode   = "light"
author = "Myian"

[Base]
base    = "#ffffff"
default = "#4c566a"
faded   = "#7b88a1"
red     = "#bf616a"
orange  = "#c97c64"
yellow  = "#daba7a"
green   = "#7cac78"
cyan    = "#6bacbe"
blue    = "#6b8ab8"
purple  = "#a36f9a"

[Project]
root     = "default"
folder   = "#d4b067"
file     = "#6d7a96"
title    = "purple"
chapter  = "blue"
scene    = "#68a593"
note     = "#a5b3ca"
active   = "green"
inactive = "faded"
disabled = "#b2c0d6"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "orange"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#e5e9f0"
windowText      = "default"
base            = "base"
alternateBase   = "#d8dee9"
text            = "default"
tooltipBase     = "#fff0d3"
tooltipText     = "default"
button          = "#e5e9f0"
buttonText      = "default"
brightText      = "base"
highlight       = "cyan"
highlightedText = "base"
link            = "blue"
linkVisited     = "blue"
accent          = "cyan"

[GUI]
helpText    = "blue"
fadedText   = "faded"
errorText   = "red"
toggle      = "blue:128"
searchMatch = "purple:80"

[Syntax]
background     = "base"
text           = "default"
line           = "#eceff4"
link           = "purple"
headerText     = "#559db1"
headerTag      = "#559db188"
emphasis       = "#549b86"
whitespace     = "#549b8664"
dialog         = "#5579a5"
altDialog      = "#619b5b"
note           = "orange"
hidden         = "faded"
shortcode      = "orange"
keyword        = "purple"
tag            = "#549481"
value          = "#549481"
optional       = "faded"
spellCheckLine = "#ff3b4f"
errorLine      = "#58aa51"
replaceTag     = "orange"
modifier       = "#a16e98"
textHighlight  = "cyan:64"
