[Main]
name   = "Primer Light"
mode   = "light"
author = "Myian"
credit = "GitHub, Inc."
url    = "https://github.com/primer"

[Base]
base    = "#ffffff"
default = "#1f2328"
faded   = "#8c959f"
red     = "#cf222e"
orange  = "#e16f24"
yellow  = "#d4a72c"
green   = "#2da44e"
cyan    = "#339d9b"
blue    = "#0969da"
purple  = "#8557db"

[Project]
root     = "#32383f"
folder   = "orange"
file     = "#49bcb7"
title    = "#116329"
chapter  = "#2e934a"
scene    = "#4ac26b"
note     = "yellow"
active   = "#24292f"
inactive = "faded"
disabled = "#afb8c1"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
altAction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "#e85aad"
markdown  = "default"
systemIO  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#eaeef2"
windowText      = "default"
base            = "base"
alternateBase   = "#dde3e8"
text            = "default"
tooltipBase     = "#fff8c5"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "green"
highlightedText = "base"
link            = "blue"
linkVisited     = "blue"
accent          = "green"
toggle          = "green:128"
searchMatch     = "#b6e3ff"

[GUI]
helpText  = "#424a53"
fadedText = "#8c959f"
errorText = "red"

[Syntax]
background     = "base"
text           = "#424a53"
line           = "#eaeef2"
link           = "blue"
headerText     = "default"
headerTag      = "#9ea7b0"
emphasis       = "#1a7f37"
whitespace     = "#1a7f3764"
dialog         = "#0d1117"
altDialog      = "cyan"
note           = "#bf8700"
hidden         = "#8c959f"
shortcode      = "#e85aad"
keyword        = "blue"
tag            = "#218bff"
value          = "orange"
optional       = "#54aeff"
spellCheckLine = "#fa4549"
errorLine      = "cyan"
replaceTag     = "purple"
modifier       = "#bc4c00"
textHighlight  = "#aceebb"
