[Main]
name   = "Primer Night"
mode   = "dark"
author = "Myian"
credit = "GitHub, Inc."
url    = "https://github.com/primer"

[Base]
base    = "#0d1117"
default = "#f0f6fc"
faded   = "#6e7681"
red     = "#ff7b72"
orange  = "#ffa657"
yellow  = "#f8e3a1"
green   = "#56d364"
cyan    = "#57CCC5"
blue    = "#79c0ff"
purple  = "#c398ff"

[Project]
root     = "default"
folder   = "orange"
file     = "#8adfd7"
title    = "#238636"
chapter  = "#56d364"
scene    = "#aff5b4"
note     = "yellow"
active   = "default"
inactive = "faded"
disabled = "#484f58"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "#ff9bce"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#161b22"
windowText      = "default"
base            = "base"
alternateBase   = "#30363d"
text            = "default"
tooltipBase     = "yellow"
tooltipText     = "base"
button          = "#21262d"
buttonText      = "default"
brightText      = "base"
highlight       = "#207c59"
highlightedText = "default"
link            = "blue"
linkVisited     = "blue"
accent          = "#207c59"

[GUI]
helpText    = "#8b949e"
fadedText   = "#6e7681"
errorText   = "#f85149"
toggle      = "#207c597f"
searchMatch = "#1f6feb80"

[Syntax]
background     = "base"
text           = "#b1bac4"
line           = "#21262d"
link           = "blue"
headerText     = "default"
headerTag      = "#b1bac4"
emphasis       = "#7ee787"
whitespace     = "#7ee78764"
dialog         = "#ffffff"
altDialog      = "#57ccc5"
note           = "#f8e3a1"
hidden         = "faded"
shortcode      = "#ff9bce"
keyword        = "#4493f8"
tag            = "blue"
value          = "#ffc680"
optional       = "#a5d6ff"
spellCheckLine = "#f85149"
errorLine      = "cyan"
replaceTag     = "purple"
modifier       = "orange"
textHighlight  = "#104c35"
