[Main]
name   = "Rosé Pine"
mode   = "dark"
author = "Myian"
credit = "Rosé Pine"
url    = "https://rosepinetheme.com"

[Base]
base    = "#191724"
default = "#e0def4"
faded   = "#908caa"
red     = "#eb6f92"
orange  = "#ebbcba"
yellow  = "#f6c177"
green   = "#88c5a1"
cyan    = "#31748f"
blue    = "#9ccfd8"
purple  = "#c4a7e7"

[Project]
root     = "default"
folder   = "orange"
file     = "default"
title    = "red"
chapter  = "cyan"
scene    = "blue"
note     = "yellow"
active   = "blue"
inactive = "red"
disabled = "#6e6a86"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
altAction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "blue"
markdown  = "default"
systemIO  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#403d52"
text            = "default"
tooltipBase     = "orange"
tooltipText     = "base"
button          = "#1f1d2e"
buttonText      = "default"
brightText      = "base"
highlight       = "red"
highlightedText = "base"
link            = "red"
linkVisited     = "red"
accent          = "red"
toggle          = "red:128"
searchMatch     = "cyan:194"

[GUI]
helpText  = "faded"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "#21202e"
link           = "red"
headerText     = "purple"
headerTag      = "purple:128"
emphasis       = "purple"
whitespace     = "purple:100"
dialog         = "red"
altDialog      = "orange"
note           = "yellow"
hidden         = "faded"
shortcode      = "cyan"
keyword        = "cyan"
tag            = "blue"
value          = "blue"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "blue"
replaceTag     = "yellow"
modifier       = "cyan"
textHighlight  = "#403d52"
