[Main]
name   = "Rosé Pine Dawn"
mode   = "light"
author = "Myian"
credit = "Rosé Pine"
url    = "https://rosepinetheme.com"

[Base]
base    = "#faf4ed"
default = "#575279"
faded   = "#797593"
red     = "#b4637a"
orange  = "#d7827e"
yellow  = "#ea9d34"
green   = "#4aa771"
cyan    = "#286983"
blue    = "#56949f"
purple  = "#9774be"

[Project]
root     = "default"
folder   = "orange"
file     = "default"
title    = "red"
chapter  = "cyan"
scene    = "blue"
note     = "yellow"
active   = "blue"
inactive = "red"
disabled = "#9893a5"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "blue"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#dfdad9"
text            = "default"
tooltipBase     = "#ebbcba"
tooltipText     = "default"
button          = "#fffaf3"
buttonText      = "default"
brightText      = "base"
highlight       = "red"
highlightedText = "base"
link            = "red"
linkVisited     = "red"
accent          = "red"
toggle          = "red:128"
searchMatch     = "blue:88"

[GUI]
helpText  = "faded"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "#f4ede8"
link           = "red"
headerText     = "purple"
headerTag      = "purple:128"
emphasis       = "purple"
whitespace     = "purple:100"
dialog         = "red"
altDialog      = "orange"
note           = "#cf8927"
hidden         = "faded"
shortcode      = "cyan"
keyword        = "cyan"
tag            = "blue"
value          = "blue"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "blue"
replaceTag     = "#cf8927"
modifier       = "cyan"
textHighlight  = "#dfdad9"
