[Main]
name   = "Ruby Day"
mode   = "light"
author = "Myian"

[Base]
base    = "#ffeeee"
default = "#444252"
faded   = "#8e8c9c"
red     = "#e46969"
orange  = "#df9355"
yellow  = "#dfb362"
green   = "#62a369"
cyan    = "#5c9da3"
blue    = "#6e73bb"
purple  = "#b67ac2"

[Project]
root     = "default"
folder   = "orange"
file     = "#757285"
title    = "green"
chapter  = "red"
scene    = "blue"
note     = "purple"
active   = "default"
inactive = "red"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "green"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#f1d9d9"
windowText      = "default"
base            = "base"
alternateBase   = "#e9c1c1"
text            = "default"
tooltipBase     = "#f0d0d0"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "red"
highlight       = "#da3d3d"
highlightedText = "base"
link            = "#da3d3d"
linkVisited     = "#da3d3d"
accent          = "#c43939"

[GUI]
helpText    = "#756777"
fadedText   = "faded"
errorText   = "red"
toggle      = "#ff9e9e"
searchMatch = "purple:104"

[Syntax]
background     = "base"
text           = "#343242"
line           = "#f3dbdd"
link           = "#5159cc"
headerText     = "#343242"
headerTag      = "#34324280"
emphasis       = "#c05858"
whitespace     = "#c0585864"
dialog         = "#ce1d1d"
altDialog      = "#c45522"
note           = "#9f58ad"
hidden         = "faded"
shortcode      = "#2a9638"
keyword        = "#5159cc"
tag            = "#9f58ad"
value          = "#b98421"
optional       = "faded"
spellCheckLine = "#ff3333"
errorLine      = "cyan"
replaceTag     = "#5159cc"
modifier       = "#2a9638"
textHighlight  = "red:104"
