[Main]
name   = "Selenium Dark"
mode   = "dark"
author = "Myian"

[Base]
base    = "#15141a"
default = "#a9a1b4"
faded   = "#625b70"
red     = "#c04358"
orange  = "#b1663a"
yellow  = "#917a3e"
green   = "#35834c"
cyan    = "#1b8186"
blue    = "#3268cc"
purple  = "#7d53b8"

[Project]
root     = "default"
folder   = "red"
file     = "default"
title    = "purple"
chapter  = "blue"
scene    = "cyan"
note     = "faded"
active   = "#c7c0d2"
inactive = "red"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "cyan"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "cyan"
create    = "yellow"
destroy   = "faded"
reset     = "cyan"
add       = "cyan"
change    = "cyan"
remove    = "red"
shortcode = "cyan"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#0f0e13"
windowText      = "#c7c0d2"
base            = "base"
alternateBase   = "#35303f"
text            = "#c7c0d2"
tooltipBase     = "default"
tooltipText     = "base"
button          = "#1e1c25"
buttonText      = "default"
brightText      = "base"
highlight       = "faded"
highlightedText = "#e4e0ec"
link            = "#9267d3"
linkVisited     = "#9267d3"
accent          = "red:D120"
toggle          = "#35303f"
searchMatch     = "#df597070"

[GUI]
helpText  = "#888095"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "#1e1c25"
link           = "blue"
headerText     = "#e4e0ec"
headerTag      = "faded"
emphasis       = "#9267d3"
whitespace     = "#9267d364"
dialog         = "#e4e0ec"
altDialog      = "#c458ac"
note           = "red"
hidden         = "faded"
shortcode      = "cyan"
keyword        = "blue"
tag            = "red"
value          = "#c7c0d2"
optional       = "#c7c0d2"
spellCheckLine = "red:L120"
errorLine      = "blue:L120"
replaceTag     = "blue"
modifier       = "cyan"
textHighlight  = "#9267d370"
