[Main]
name   = "Sultana Light"
mode   = "light"
author = "Myian"

[Base]
base    = "#fff6f6"
default = "#494657"
faded   = "#a89d98"
red     = "#d3677e"
orange  = "#d6805e"
yellow  = "#cc9c49"
green   = "#819c42"
cyan    = "#5f9c88"
blue    = "#6591b6"
purple  = "#a279b9"

[Project]
root     = "#5a5563"
folder   = "orange"
file     = "blue"
title    = "red"
chapter  = "yellow"
scene    = "green"
note     = "faded"
active   = "#77606e"
inactive = "red"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "orange"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#f0e4e4"
windowText      = "default"
base            = "base"
alternateBase   = "#e4cccc"
text            = "default"
tooltipBase     = "#ffeac6"
tooltipText     = "default"
button          = "#fcf3f3"
buttonText      = "default"
brightText      = "base"
highlight       = "#c57b85"
highlightedText = "#f9f4fc"
link            = "#5577bb"
linkVisited     = "#5577bb"
accent          = "#ad6978"

[GUI]
helpText    = "default:192"
fadedText   = "faded"
errorText   = "red"
toggle      = "#ad69787f"
searchMatch = "yellow:80"

[Syntax]
background     = "base"
text           = "#77606e"
line           = "#f0e4e4"
link           = "#5577bb"
headerText     = "#66515e"
headerTag      = "#66515e80"
emphasis       = "#5577bb"
whitespace     = "#5577bb64"
dialog         = "#c54a5f"
altDialog      = "#4d968a"
note           = "#699128"
hidden         = "#aa9292"
shortcode      = "#4d968a"
keyword        = "#b89126"
tag            = "#4d968a"
value          = "#c77741"
optional       = "#aa9292"
spellCheckLine = "#ec5656"
errorLine      = "#42a789"
replaceTag     = "#ab69d1"
modifier       = "#b89126"
textHighlight  = "#b8788366"
