[Main]
name   = Today Tritanopia
mode   = light
author = Veronica Berglyd Olsen

##
# Colours:
# Background   = #ffffff
# Foreground   = #242424
# Comment      = #606060
#
# Comparison: Original to Simulated Tritanopia
# Red          = #cc0000 -> #cd003c
# Orange       = #ff6600 -> #ff5a77
# Yellow       = #ffcc00 -> #d38e95
# Green        = #009933 -> #37918c
# Aqua         = #00cccc -> #00cdc5
# Blue         = #0066cc -> #007c75
# Purple       = #6600cc -> #3c5351
##

[Base]
base    = #ffffff
default = #242424
faded   = #606060

# Full Colour Vision
red     = #cc0000
orange  = #ff6600
yellow  = #ffcc00
green   = #009933
cyan    = #00cccc
blue    = #0066cc
purple  = #6600cc

# Simulated Tritanopia
# red     = #cd003c
# orange  = #ff5a77
# yellow  = #d38e95
# green   = #37918c
# cyan    = #00cdc5
# blue    = #007c75
# purple  = #3c5351

[Project]
root     = green
folder   = yellow
file     = default
title    = green
chapter  = red
scene    = green
note     = yellow
active   = green
inactive = red
disabled = faded

[Icon]
tool      = default
sidebar   = default
accept    = green
reject    = red
action    = default
altaction = orange
apply     = green
create    = yellow
destroy   = faded
reset     = green
add       = green
change    = green
remove    = yellow
shortcode = default
markdown  = orange
systemio  = yellow
info      = cyan
warning   = orange
error     = red

[Palette]
window          = base:D105
windowtext      = default
base            = base
alternatebase   = #e0e0e0
text            = default
tooltipbase     = #ffffc0
tooltiptext     = #15150d
button          = #efefef
buttontext      = default
brighttext      = base
highlight       = green:128
highlightedtext = base
link            = green
linkvisited     = green
accent          = green:L150

[GUI]
helptext  = green:D110
fadedtext = faded
errortext = red

[Syntax]
background     = base
text           = default
line           = default:32
link           = green
headertext     = green
headertag      = green:160
emphasis       = orange
whitespace     = yellow:64
dialog         = green
altdialog      = yellow:D125
note           = yellow:D125
hidden         = faded
shortcode      = yellow:D125
keyword        = red
tag            = green
value          = orange
optional       = yellow:D125
spellcheckline = red
errorline      = yellow:D125
replacetag     = yellow:D125
modifier       = red
texthighlight  = yellow:96
