[Main]
name   = Today Deuteranopia
mode   = light
author = Veronica Berglyd Olsen

##
# Colours:
# Background   = #ffffff
# Foreground   = #242424
# Comment      = #606060
#
# Comparison: Original to Simulated Deuteranopia
# Red          = #cc0000 -> #757500
# Orange       = #ff6600 -> #a7a700
# Yellow       = #ffcc00 -> #dddd00
# Green        = #009933 -> #838338
# Aqua         = #00cccc -> #afafce
# Blue         = #0066cc -> #5656cc
# Purple       = #6600cc -> #3838cc
##

[Base]
base    = #ffffff
default = #242424
faded   = #606060

# Full Colour Vision
# red     = #cc0000
# orange  = #ff6600
# yellow  = #ffcc00
# green   = #009933
# cyan    = #00cccc
# blue    = #0066cc
# purple  = #6600cc

# Simulated Deuteranopia
red     = #757500
orange  = #a7a700
yellow  = #dddd00
green   = #838338
cyan    = #afafce
blue    = #5656cc
purple  = #3838cc

[Project]
root     = blue
folder   = yellow
file     = default
title    = blue
chapter  = blue
scene    = blue
note     = yellow
active   = blue
inactive = red
disabled = faded

[Icon]
tool      = default
sidebar   = default
accept    = blue
reject    = red
action    = blue
altaction = orange
apply     = green
create    = yellow
destroy   = faded
reset     = green
add       = green
change    = green
remove    = yellow
shortcode = default
markdown  = orange
systemio  = yellow
info      = blue
warning   = orange
error     = red

[Palette]
window          = base:D105
windowtext      = default
base            = base
alternatebase   = #e0e0e0
text            = default
tooltipbase     = #ffffc0
tooltiptext     = #15150d
button          = #efefef
buttontext      = default
brighttext      = base
highlight       = blue:L150
highlightedtext = base
link            = blue
linkvisited     = blue
accent          = blue:L150

[GUI]
helptext  = blue
fadedtext = faded
errortext = yellow

[Syntax]
background     = base
text           = default
line           = default:32
link           = blue
headertext     = blue
headertag      = blue:160
emphasis       = yellow:D125
whitespace     = yellow:64
dialog         = blue
altdialog      = yellow:D125
note           = yellow:D125
hidden         = faded
shortcode      = yellow:D125
keyword        = green
tag            = blue
value          = green
optional       = yellow:D125
spellcheckline = blue
errorline      = yellow:D125
replacetag     = yellow:D125
modifier       = green
texthighlight  = yellow:96
