[Main]
name   = "Vivid White Red"
mode   = "light"
author = "Myian"

[Base]
base    = "#ffffff"
default = "#222127"
faded   = "#78748a"
red     = "#e72b44"
orange  = "#e46802"
yellow  = "#bd9205"
green   = "#009e1a"
cyan    = "#0093a7"
blue    = "#3d58f1"
purple  = "#7c17ff"

#magenta = #ed14f5

[Project]
root     = "default"
folder   = "yellow"
file     = "faded"
title    = "purple"
chapter  = "#ed14f5"
scene    = "red"
note     = "green"
active   = "red"
inactive = "faded"
disabled = "faded:L135"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "default"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "cyan"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#d8dce0"
text            = "default"
tooltipBase     = "red:L175"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "red"
highlightedText = "base"
link            = "red"
linkVisited     = "red"
accent          = "red"
toggle          = "red:96"
searchMatch     = "green:72"

[GUI]
helpText  = "default:L250"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "#f3f3f8"
link           = "blue"
headerText     = "yellow"
headerTag      = "yellow:128"
emphasis       = "orange"
whitespace     = "orange:64"
dialog         = "red"
altDialog      = "#a37e03"
note           = "green"
hidden         = "faded"
shortcode      = "cyan"
keyword        = "#ed14f5"
tag            = "purple"
value          = "blue"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "cyan"
replaceTag     = "#ed14f5"
modifier       = "cyan"
textHighlight  = "red:72"
