[Main]
name   = "Vivid Black Red"
mode   = "dark"
author = "Myian"

[Base]
base    = "#0c0f16"
default = "#f1f1f1"
faded   = "#888e9e"
red     = "#ff3a64"
orange  = "#ff823e"
yellow  = "#fff461"
green   = "#3dff5d"
cyan    = "#3ff3f0"
blue    = "#2f9aff"
purple  = "#ae70ff"

#magenta = #ff61e5

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "purple"
chapter  = "#ff61e5"
scene    = "red"
note     = "green"
active   = "red"
inactive = "faded"
disabled = "faded:D175"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "default"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "cyan"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#323742"
text            = "default"
tooltipBase     = "red:L150"
tooltipText     = "base"
button          = "#131622"
buttonText      = "default"
brightText      = "base"
highlight       = "red"
highlightedText = "base"
link            = "red"
linkVisited     = "red"
accent          = "red"
toggle          = "red:128"
searchMatch     = "green:72"

[GUI]
helpText  = "faded"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "#1c1f27"
link           = "blue"
headerText     = "yellow"
headerTag      = "yellow:128"
emphasis       = "orange"
whitespace     = "orange:64"
dialog         = "red"
altDialog      = "yellow"
note           = "green"
hidden         = "faded"
shortcode      = "cyan"
keyword        = "#ff61e5"
tag            = "purple"
value          = "blue"
optional       = "faded"
spellCheckLine = "#ff3737"
errorLine      = "cyan"
replaceTag     = "#ff61e5"
modifier       = "cyan"
textHighlight  = "red:80"
