[Main]
name   = "Warpgate"
mode   = "dark"
author = "Myian"
credit = "PlanetSide 2"

[Base]
base    = "#06232a"
default = "#f9fcfd"
faded   = "#729faa"
red     = "#fb564a"
orange  = "#f67e0a"
yellow  = "#fbcd42"
green   = "#5dff6a"
cyan    = "#2ee7f8"
blue    = "#74a0f6"
purple  = "#c07efc"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "red"
chapter  = "purple"
scene    = "blue"
note     = "green"
active   = "green"
inactive = "red"
disabled = "faded"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
altAction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "orange"
markdown  = "default"
systemIO  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base:D150"
windowText      = "default"
base            = "base"
alternateBase   = "#1a5463"
text            = "default"
tooltipBase     = "#c2ffaa"
tooltipText     = "base"
button          = "#00252e"
buttonText      = "default"
brightText      = "base"
highlight       = "#58d662"
highlightedText = "base"
link            = "green"
linkVisited     = "green"
accent          = "green"
toggle          = "cyan:80"
searchMatch     = "green:128"

[GUI]
helpText  = "faded"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "base:L150"
link           = "green"
headerText     = "green"
headerTag      = "green:128"
emphasis       = "#fff6aa"
whitespace     = "#fff6aa64"
dialog         = "cyan"
altDialog      = "#11bdc6"
note           = "green"
hidden         = "faded"
shortcode      = "orange"
keyword        = "orange"
tag            = "yellow"
value          = "yellow"
optional       = "faded"
spellCheckLine = "#ff4444"
errorLine      = "green"
replaceTag     = "green"
modifier       = "orange"
textHighlight  = "#1a5463"
