[Main]
name   = "Waterlily Dark"
mode   = "dark"
author = "Myian"

[Base]
base    = "#1e2b33"
default = "#d0dee6"
faded   = "#7b8e99"
red     = "#ff7474"
orange  = "#fca469"
yellow  = "#f7eaa4"
green   = "#9ae37f"
cyan    = "#8ef3d1"
blue    = "#71caeb"
purple  = "#c89dfd"

[Project]
root     = "default"
folder   = "blue"
file     = "purple"
title    = "green"
chapter  = "yellow"
scene    = "#ff9fbd"
note     = "faded"
active   = "#ff9fbd"
inactive = "faded"
disabled = "#3e5366"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
altAction = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "green"
systemIO  = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#151f25"
windowText      = "default"
base            = "base"
alternateBase   = "#3b515f"
text            = "default"
tooltipBase     = "#ffbad0"
tooltipText     = "base"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#87bcc0"
highlightedText = "base"
link            = "blue"
linkVisited     = "blue"
accent          = "#ff9fbd"
toggle          = "blue:80"
searchMatch     = "purple:80"

[GUI]
helpText  = "faded"
fadedText = "faded"
errorText = "red"

[Syntax]
background     = "base"
text           = "default"
line           = "#283842"
link           = "blue"
headerText     = "#e8eef1"
headerTag      = "faded"
emphasis       = "green"
whitespace     = "green:64"
dialog         = "#ff9fbd"
altDialog      = "orange"
note           = "blue"
hidden         = "faded"
shortcode      = "purple"
keyword        = "purple"
tag            = "yellow"
value          = "cyan"
optional       = "faded"
spellCheckLine = "#ff5d5d"
errorLine      = "#4ae698"
replaceTag     = "blue"
modifier       = "purple"
textHighlight  = "blue:64"
