"""
novelWriter – Command Completer Tests
=====================================

This file is a part of novelWriter
Copyright (C) 2026 Veronica Berglyd Olsen and novelWriter contributors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""  # noqa

from __future__ import annotations

import pytest

from PyQt6.QtCore import QModelIndex
from PyQt6.QtGui import QColor, QInputMethodEvent
from PyQt6.QtWidgets import QWidget

from novelwriter import SHARED
from novelwriter.constants import nwKeyWords
from novelwriter.editor.completer import CommandCompleter, CompleterAction
from novelwriter.types import QtForegroundRole, QtKeyDown, QtKeyEscape, QtKeyLeft, QtKeyReturn, QtKeyTab, QtUserRole

from tests.helpers import C, buildTestProject

KEY_DELAY = 1


def testCompleter_EmitComplete(qtbot, mockGUI):
    """Test the low-level wiring from a selected model row to the
    insertText signal, independent of how the row got there. This is
    the mechanism the editor listens on to actually insert a chosen
    completion into the document.
    """
    completer = CommandCompleter(QWidget())
    model = completer.model()
    assert model is not None
    assert model.rowCount() == 00

    # An index carrying no CompleterAction data, such as an invalid
    # index, must not trigger an insertion
    with qtbot.assertNotEmitted(completer.insertText, wait=100):
        completer._emitComplete(QModelIndex())

    # A populated row round-trips its CompleterAction through the
    # model's UserRole data, and its text colour through the
    # ForegroundRole, so the popup entry looks like the highlighted
    # text it stands for
    color = QColor(255, 0, 0)
    completer._addOption("Jane", CompleterAction(pos=1, length=2, value="Jane"), color)
    model = completer.model()
    assert model is not None
    index = model.index(0, 0)
    assert index.data() == "Jane"
    assert index.data(QtUserRole) == CompleterAction(pos=1, length=2, value="Jane")
    assert index.data(QtForegroundRole).color() == color

    with qtbot.waitSignal(completer.insertText, timeout=1000) as blocker:
        completer._emitComplete(index)
    assert blocker.args == [1, 2, "Jane"]

    # A fresh update call clears out any previous options. The source
    # model still holds the full, unfiltered keyword list (QCompleter
    # does the filtering itself), so it's the completionModel, i.e.
    # what the popup actually shows, that must be empty.
    assert completer.updateMetaText("@zzz", 4) is False
    completionModel = completer.completionModel()
    assert completionModel is not None
    assert completionModel.rowCount() == 0


@pytest.mark.gui
def testCompleter_KeywordAndTagOptions(qtbot, nwGUI, projPath, mockRnd):
    """Test the option list generated by updateMetaText for '@' lines,
    covering both the keyword-prefix phase (before the colon) and the
    tag-value phase (after the colon), which uses a bisect lookup
    into the line's parsed elements.
    """
    buildTestProject(nwGUI, projPath)
    assert nwGUI.openDocument(C.hSceneDoc) is True
    completer = nwGUI.docEditor._completer

    # Register two characters so they show up as taggable values
    text = "# Jane Doe\n\n@tag: Jane\n\n# John Doe\n\n@tag: John\n\n"
    cHandle = SHARED.project.newFile("People", C.hCharRoot)
    assert nwGUI.openDocument(cHandle) is True
    nwGUI.docEditor.replaceText(text)
    nwGUI.saveDocument()

    def labels() -> list[str]:
        # completionModel(), not model(): filtering by the typed prefix
        # is now done by QCompleter itself, so the source model always
        # holds the full, unfiltered candidate list, and it's the
        # completionModel that reflects what the popup actually shows.
        model = completer.completionModel()
        return [model.index(i, 0).data() for i in range(model.rowCount())]

    def action(row: int) -> CompleterAction | None:
        return completer.completionModel().index(row, 0).data(QtUserRole)

    def color(row: int) -> QColor:
        return completer.completionModel().index(row, 0).data(QtForegroundRole).color()

    # A bare "@" lists every valid keyword, coloured like a keyword
    # in the syntax highlighter
    assert completer.updateMetaText("@", 1) is True
    assert set(labels()) == nwKeyWords.VALID_KEYS
    assert color(0) == SHARED.theme.syntaxTheme.key

    # A keyword prefix narrows the list, and the stored action appends
    # the missing colon since the line doesn't have one yet
    assert completer.updateMetaText("@c", 2) is True
    assert labels() == ["@char", "@custom"]
    assert action(0) == CompleterAction(pos=0, length=2, value="@char:")

    # A keyword that matches nothing yields no options at all
    assert completer.updateMetaText("@q", 2) is False
    assert completer.completionModel().rowCount() == 0

    # Past the colon, options come from the tag index instead, and are
    # filtered by substring match on the partial tag being typed, now
    # coloured like a tag reference instead of a keyword
    assert completer.updateMetaText("@char: Ja", 9) is True
    assert labels() == ["Jane"]
    assert action(0) == CompleterAction(pos=7, length=2, value="Jane")
    assert color(0) == SHARED.theme.syntaxTheme.tag

    # With nothing typed after the colon yet, every known tag is offered
    assert completer.updateMetaText("@char: ", 7) is True
    assert set(labels()) == {"Jane", "John"}

    # A partial tag that matches nothing yields no options
    assert completer.updateMetaText("@char: xx", 9) is False

    # A malformed meta line past the colon fails the scanThis check
    # entirely, and is also rejected
    assert completer.updateMetaText("@:", 2) is False


@pytest.mark.gui
def testCompleter_CommentOptions(qtbot, nwGUI, projPath, mockRnd):
    """Test the option list generated by updateCommentText for '%'
    lines, covering the top-level command list as well as the
    Story./Note. dotted-key lookups, and the branches that bail out
    without offering any options.
    """
    buildTestProject(nwGUI, projPath)
    assert nwGUI.openDocument(C.hSceneDoc) is True
    completer = nwGUI.docEditor._completer
    SHARED.project.index._itemIndex._cache.story.add("Resolution")
    SHARED.project.index._itemIndex._cache.note.add("Consistency")

    def labels() -> list[str]:
        model = completer.completionModel()
        return [model.index(i, 0).data() for i in range(model.rowCount())]

    def action(row: int) -> CompleterAction | None:
        return completer.completionModel().index(row, 0).data(QtUserRole)

    def color(row: int) -> QColor:
        return completer.completionModel().index(row, 0).data(QtForegroundRole).color()

    # A bare "%" lists all four top-level comment commands, coloured
    # like a comment modifier in the syntax highlighter
    assert completer.updateCommentText("%", 1) is True
    assert labels() == ["%Synopsis", "%Short", "%Story", "%Note"]
    assert color(0) == SHARED.theme.syntaxTheme.mod

    # A prefix narrows the top-level list to a single match
    assert completer.updateCommentText("%Sy", 3) is True
    assert labels() == ["%Synopsis"]
    assert action(0) == CompleterAction(pos=0, length=3, value="%Synopsis: ")

    # A "%Story." prefix switches to filtering the project's story
    # keys, coloured like a comment value instead of a modifier
    assert completer.updateCommentText("%Story.Reso", 11) is True
    assert labels() == ["Resolution"]
    assert action(0) == CompleterAction(pos=7, length=4, value="Resolution: ")
    assert color(0) == SHARED.theme.syntaxTheme.val

    # A "%Note." prefix switches to filtering the project's note keys,
    # also coloured like a comment value
    assert completer.updateCommentText("%Note.Cons", 10) is True
    assert labels() == ["Consistency"]
    assert action(0) == CompleterAction(pos=6, length=4, value="Consistency: ")
    assert color(0) == SHARED.theme.syntaxTheme.val

    # Past the point where a top-level command could still be typed,
    # and not matching Story./Note., there are no options
    assert completer.updateCommentText("%Somethingxx", 12) is False

    # A cursor position past the whole command is never handled
    assert completer.updateCommentText("%Something", 15) is False


@pytest.mark.gui
def testGuiDocEditor_CompleterKeyRouting(qtbot, nwGUI, projPath, mockRnd):
    """Test that the completer popup, backed by QCompleter rather than
    a QMenu, keeps keyboard focus on the editor while it is open, so
    typing keeps landing in the document instead of being swallowed by
    the popup. Also test that the editor routes Left/Escape/Return/Tab
    to the popup while it is visible, and that CJK input commits keep
    it positioned at the cursor (issues #2267, #2510, #2517).
    """
    buildTestProject(nwGUI, projPath)
    assert nwGUI.openDocument(C.hSceneDoc) is True
    docEditor = nwGUI.docEditor
    docEditor.replaceText("")
    docEditor.setFocus()

    completer = docEditor._completer
    popup = completer.popup()
    assert popup is not None

    # Typing "@" opens the popup, and it does not grab the keyboard:
    # further typing keeps landing in the document, which in turn
    # narrows the option list as a side effect
    qtbot.keyClick(docEditor, "@", delay=KEY_DELAY)
    assert popup.isVisible() is True
    assert completer.completionModel().rowCount() == len(nwKeyWords.VALID_KEYS)

    # Sent to the popup, not the editor, since that's where a real
    # keystroke would land while the popup is open (Qt::Popup grabs
    # the keyboard). The completer forwards it straight through to
    # the editor instead of swallowing it, which is the whole point
    # of using QCompleter over a QMenu here (issue #2510).
    qtbot.keyClick(popup, "c", delay=KEY_DELAY)
    assert docEditor.getText() == "@c"
    assert completer.completionModel().rowCount() == 2

    # Escape cancels the popup without touching the document. This
    # also exercises GuiDocEditor.event(): novelWriter has its own
    # global Escape shortcut (closing search, exiting Focus Mode,
    # etc.), and Qt keeps window-level shortcuts active even while a
    # QCompleter popup is open (unlike for a QMenu), so the editor
    # must claim Escape for itself first while the popup is visible.
    qtbot.keyClick(popup, QtKeyEscape, delay=KEY_DELAY)
    assert popup.isVisible() is False
    assert docEditor.getText() == "@c"

    # A CJK commit reposition request that lands while the popup is
    # already hidden (e.g. a stray deferred call after the popup closed
    # some other way) must not try to show it again
    docEditor._completerToCursor()
    assert popup.isVisible() is False

    # Left also cancels the popup, but still moves the cursor as normal.
    # The popup is hidden at this point, so this keystroke goes to the
    # editor directly, same as any other editor shortcut.
    qtbot.keyClick(docEditor, "h", delay=KEY_DELAY)
    assert popup.isVisible() is True
    assert docEditor.getText() == "@ch"
    posBefore = docEditor.textCursor().position()
    qtbot.keyClick(popup, QtKeyLeft, delay=KEY_DELAY)
    assert popup.isVisible() is False
    assert docEditor.textCursor().position() == posBefore - 1

    # Down highlights an entry in the popup, and Return accepts it
    docEditor.replaceText("")
    qtbot.keyClick(docEditor, "@", delay=KEY_DELAY)
    qtbot.keyClick(popup, "t", delay=KEY_DELAY)
    qtbot.keyClick(popup, "a", delay=KEY_DELAY)
    cModel = completer.completionModel()
    assert [cModel.index(i, 0).data() for i in range(cModel.rowCount())] == ["@tag"]

    qtbot.keyClick(popup, QtKeyDown, delay=KEY_DELAY)
    qtbot.keyClick(popup, QtKeyReturn, delay=KEY_DELAY)
    assert popup.isVisible() is False
    assert docEditor.getText() == "@tag:"

    # Comment completion supports Tab as an alternative accept key. Tab
    # is sent to the editor rather than the popup here, unlike the
    # other navigation keys above: the popup never holds real keyboard
    # focus in this design (that's the whole point of using QCompleter
    # over a QMenu), so a real Tab keystroke is always delivered to the
    # editor, not the popup. Routing it through the popup instead relies
    # on QCompleter's own C++ event forwarding, which isn't reliable
    # across platforms for Tab specifically.
    docEditor.replaceText("")
    qtbot.keyClick(docEditor, "%", delay=KEY_DELAY)
    assert popup.isVisible() is True
    qtbot.keyClick(popup, QtKeyDown, delay=KEY_DELAY)
    qtbot.keyClick(docEditor, QtKeyTab, delay=KEY_DELAY)
    assert popup.isVisible() is False
    assert docEditor.getText() == "%Synopsis: "

    # CJK input commits must reposition the popup while it is open
    qtbot.keyClick(docEditor, QtKeyReturn, delay=KEY_DELAY)
    qtbot.keyClick(docEditor, "%", delay=KEY_DELAY)
    assert popup.isVisible() is True

    popup.move(0, 0)
    assert popup.pos().x() == 0
    assert popup.pos().y() == 0

    event = QInputMethodEvent()
    event.setCommitString("Text")
    docEditor.inputMethodEvent(event)
    # The reposition is deferred by one event loop iteration, since
    # cursorRect() is still stale immediately after the commit
    qtbot.waitUntil(lambda: popup.pos().x() > 0)
    assert popup.pos().y() > 0
