name: Linux (3.6)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  pyTest36:
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
          architecture: x64
      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install xvfb libenchant-dev qt5-default
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyVirtualDisplay
          pip install pytest-timeout
          pip install pytest-xvfb
          pip install pytest-qt
      - name: Run Tests
        run: xvfb-run pytest -v --timeout=60
