name: macOS (3.8)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  pyTestMac38:
    runs-on: macos-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Packages
        run: |
          brew cask install xquartz
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyVirtualDisplay
          pip install pytest-timeout
          pip install pytest-xvfb
          pip install pytest-qt
      - name: Run Tests
        run: xvfb-run pytest -v --timeout=60
