name: Linting

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  checkSyntax:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install Dependencies
        run: |
          pdm install --prod --group lint

      - name: Ruff Check
        run: |
          pdm run ruff --version
          pdm run ruff check --output-format github

      - name: Pyright Check
        run: |
          pdm run pyright --version
          pdm run pyright

      - name: Isort Check
        run: |
          pdm run isort --version
          pdm run isort --check .
