name: Linux

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  testLinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
      fail-fast: false
    name: Test Python ${{ matrix.python-version }}
    permissions:
      contents: read
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6

      - name: Install System Packages
        run: |
          sudo apt update
          sudo apt install qttools5-dev-tools

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pdm install --group test

      - name: Build Assets
        run: |
          pdm run pkgutils.py qtlrelease
          pdm run pkgutils.py sample

      - name: Run Tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pdm run coverage run -m pytest -v --timeout=60
          pdm run coverage xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  testUbuntu24:
    name: Test Ubuntu 24.04 & Sys Packages
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6

      - name: Install System Packages
        run: |
          sudo apt update
          sudo apt install \
            python3-pyqt6 \
            python3-pyqt6.qtsvg \
            python3-pytest \
            python3-pytestqt \
            python3-enchant \
            python3-pytest-timeout \
            qt6-image-formats-plugins

      - name: Build Assets
        run: |
          python3 pkgutils.py sample

      - name: Run Tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          python3 -m pytest -v --timeout=60
