name: Linux (3.7)

on:
  push:
    branches: [ main, testing, dev ]
  pull_request:
    branches: [ main, testing, dev ]

jobs:
  testLinux37:
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install libenchant-dev qt5-default
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-timeout
          pip install pytest-qt
      - name: Run Tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          pytest -v --timeout=60
